import type { Activity, Community, Recipe, TrainingPlan, Goal } from './types'

// Ciudades de Latam
export const LATAM_CITIES = [
  'Buenos Aires, Argentina',
  'La Plata, Argentina',
  'Córdoba, Argentina',
  'Rosario, Argentina',
  'Mendoza, Argentina',
  'Montevideo, Uruguay',
  'São Paulo, Brasil',
  'Rio de Janeiro, Brasil',
  'Santiago, Chile',
  'Lima, Perú',
  'Bogotá, Colombia',
  'Medellín, Colombia',
  'Quito, Ecuador',
  'Guayaquil, Ecuador',
  'Ciudad de México, México',
  'Guadalajara, México',
  'Monterrey, México',
  'Caracas, Venezuela',
  'San José, Costa Rica',
  'Ciudad de Panamá, Panamá',
  'La Paz, Bolivia',
  'Santa Cruz, Bolivia',
  'Asunción, Paraguay',
  'San Salvador, El Salvador',
  'Tegucigalpa, Honduras',
  'Managua, Nicaragua',
  'San Juan, Puerto Rico',
  'La Habana, Cuba',
  'Santo Domingo, República Dominicana',
  'Guatemala, Guatemala',
]

const now = Date.now()

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '1',
    sport: 'running',
    title: 'Morning Run 5K',
    distanceKm: 5.2,
    durationMin: 28,
    createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
    avgPaceMinPerKm: 5.4,
    elevationM: 45,
    effort: 'moderate',
    author: { id: '1', name: 'Juan Pérez', username: '@juanp', avatar: '👨‍🦱', level: 'intermediate', city: 'Buenos Aires' },
    likes: 23,
    comments: 5,
    isLiked: false,
    note: '¡Excelente sesión matutina! Me sentí muy bien hoy.',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=600&fit=crop' },
  },
  {
    id: '2',
    sport: 'cycling',
    title: 'Ciclismo de ruta',
    distanceKm: 42.5,
    durationMin: 95,
    createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    elevationM: 320,
    effort: 'hard',
    author: { id: '2', name: 'María González', username: '@mariag', avatar: '👩‍🦰', level: 'advanced', city: 'La Plata' },
    likes: 45,
    comments: 12,
    isLiked: true,
    note: 'Ruta increíble por las sierras. El clima estuvo perfecto 🌤️',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=600&fit=crop' },
  },
  {
    id: '3',
    sport: 'swim',
    title: 'Entrenamiento de natación',
    distanceKm: 2.1,
    durationMin: 52,
    createdAt: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
    effort: 'moderate',
    author: { id: '3', name: 'Carlos Rodríguez', username: '@carlosr', avatar: '👨‍🦲', level: 'intermediate', city: 'Montevideo' },
    likes: 18,
    comments: 3,
    isLiked: false,
    note: 'Series de 400m. Mejoré mis tiempos en un 5%',
  },
  {
    id: '4',
    sport: 'strength',
    title: 'Partido amistoso',
    durationMin: 90,
    createdAt: new Date(now - 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 24 * 60 * 60 * 1000).toISOString(),
    effort: 'hard',
    author: { id: '4', name: 'Diego Martínez', username: '@diegom', avatar: '👨‍🦱', level: 'intermediate', city: 'Santiago' },
    likes: 67,
    comments: 18,
    isLiked: false,
    note: '¡Ganamos 3-2! Metí un gol de tiro libre ⚽🔥',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&h=600&fit=crop' },
  },
  {
    id: '5',
    sport: 'gym',
    title: 'Día de piernas',
    durationMin: 75,
    createdAt: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 30 * 60 * 60 * 1000).toISOString(),
    effort: 'max',
    author: { id: '5', name: 'Ana López', username: '@anita_fit', avatar: '👩‍🦱', level: 'advanced', city: 'Lima' },
    likes: 92,
    comments: 24,
    isLiked: true,
    note: 'Sentadillas 5x5 con 80kg. Nuevo PR personal! 💪',
  },
  {
    id: '6',
    sport: 'yoga',
    title: 'Yoga Vinyasa Flow',
    durationMin: 60,
    createdAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    effort: 'easy',
    author: { id: '6', name: 'Laura Fernández', username: '@laura_zen', avatar: '👩', level: 'intermediate', city: 'Bogotá' },
    likes: 34,
    comments: 7,
    isLiked: false,
    note: 'Sesión de recuperación después de la semana intensa 🧘‍♀️✨',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop' },
  },
  {
    id: '7',
    sport: 'running',
    title: 'Intervalos de velocidad',
    distanceKm: 8.5,
    durationMin: 38,
    createdAt: new Date(now - 2 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 2 * 24 * 60 * 60 * 1000 - 6 * 60 * 60 * 1000).toISOString(),
    avgPaceMinPerKm: 4.5,
    elevationM: 12,
    effort: 'hard',
    author: { id: '7', name: 'Pedro Sánchez', username: '@pedros_run', avatar: '👨', level: 'advanced', city: 'Medellín' },
    likes: 41,
    comments: 9,
    isLiked: true,
    note: '8x800m a ritmo de 5K. Me sentí muy fuerte en las últimas repeticiones! 🔥',
  },
  {
    id: '8',
    sport: 'running',
    title: 'Cerro Campanario',
    distanceKm: 12.3,
    durationMin: 210,
    createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
    elevationM: 850,
    effort: 'max',
    author: { id: '8', name: 'Sofía Torres', username: '@sofi_mountains', avatar: '👩‍🦳', level: 'advanced', city: 'Quito' },
    likes: 156,
    comments: 31,
    isLiked: false,
    note: 'Vistas espectaculares! El esfuerzo valió totalmente la pena 🏔️😍',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=600&fit=crop' },
  },
  {
    id: '9',
    sport: 'cycling',
    title: 'Rodada de recuperación',
    distanceKm: 25.0,
    durationMin: 72,
    createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000 - 10 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 3 * 24 * 60 * 60 * 1000 - 10 * 60 * 60 * 1000).toISOString(),
    elevationM: 95,
    effort: 'easy',
    author: { id: '9', name: 'Roberto Paz', username: '@rober_bike', avatar: '👨‍🦲', level: 'intermediate', city: 'Guadalajara' },
    likes: 28,
    comments: 4,
    isLiked: false,
    note: 'Recuperación activa después del evento del domingo. Piernas un poco cargadas pero bien.',
  },
  {
    id: '10',
    sport: 'swim',
    title: 'Aguas abiertas - Entrenamiento',
    distanceKm: 3.8,
    durationMin: 68,
    createdAt: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    effort: 'hard',
    author: { id: '10', name: 'Valentina Costa', username: '@vale_swim', avatar: '👩‍🦱', level: 'elite', city: 'Rosario' },
    likes: 73,
    comments: 15,
    isLiked: true,
    note: 'Preparándome para la competencia del próximo mes. El agua estuvo fría pero genial 🌊',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=600&fit=crop' },
  },
  {
    id: '11',
    sport: 'running',
    title: 'Entrenamiento grupal',
    distanceKm: 7.5,
    durationMin: 42,
    createdAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    avgPaceMinPerKm: 5.6,
    elevationM: 28,
    effort: 'moderate',
    author: { id: '11', name: 'Martín Gómez', username: '@martin_run', avatar: '👨‍🦰', level: 'intermediate', city: 'Córdoba' },
    likes: 38,
    comments: 14,
    isLiked: false,
    note: '¡Salida increíble con el grupo de running! Conocí gente muy copada y la ruta estuvo espectacular. Ya coordinamos para la próxima 🏃‍♂️👥',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?w=800&h=600&fit=crop' },
  },
  {
    id: '12',
    sport: 'cycling',
    title: 'Rodada social dominical',
    distanceKm: 55.0,
    durationMin: 148,
    createdAt: new Date(now - 6 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 6 * 24 * 60 * 60 * 1000).toISOString(),
    elevationM: 420,
    effort: 'moderate',
    author: { id: '12', name: 'Lucía Morales', username: '@luci_bike', avatar: '👩‍🦱', level: 'advanced', city: 'Mendoza' },
    likes: 89,
    comments: 22,
    isLiked: true,
    note: 'Domingo perfecto con más de 30 ciclistas! Parada para café incluida ☕🚴‍♀️ La mejor manera de empezar la semana es conociendo gente nueva que comparte tu pasión 💚',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1511994714008-b6c40945f5f8?w=800&h=600&fit=crop' },
  },
  {
    id: '13',
    sport: 'yoga',
    title: 'Clase grupal en el parque',
    durationMin: 75,
    createdAt: new Date(now - 7 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 7 * 24 * 60 * 60 * 1000).toISOString(),
    effort: 'easy',
    author: { id: '13', name: 'Camila Paz', username: '@cami_yoga', avatar: '👩', level: 'intermediate', city: 'Buenos Aires' },
    likes: 56,
    comments: 18,
    isLiked: false,
    note: '¡Sesión mágica al aire libre! 🌅 Más de 20 personas compartiendo energía positiva. Si están en Palermo, sumense los sábados 8am 🧘‍♀️✨',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&h=600&fit=crop' },
  },
  {
    id: '14',
    sport: 'running',
    title: 'Carrera benéfica 10K',
    distanceKm: 10.0,
    durationMin: 54,
    createdAt: new Date(now - 8 * 24 * 60 * 60 * 1000).toISOString(),
    startAt: new Date(now - 8 * 24 * 60 * 60 * 1000).toISOString(),
    avgPaceMinPerKm: 5.4,
    elevationM: 15,
    effort: 'moderate',
    author: { id: '14', name: 'Gabriel Torres', username: '@gabi_runner', avatar: '👨', level: 'intermediate', city: 'La Plata' },
    likes: 125,
    comments: 35,
    isLiked: true,
    note: 'Participé de la carrera solidaria y fue una experiencia increíble! 💛 Más de 500 corredores ayudando a una gran causa. El deporte une y transforma 🏃‍♂️❤️',
    photo: { kind: 'url', url: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&h=600&fit=crop' },
  },
]

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'c1',
    name: 'Corredores de Buenos Aires',
    sport: 'running',
    description: 'Grupo de running en Buenos Aires. Salidas semanales todos los sábados 7 AM en Palermo.',
    members: 1247,
    isJoined: true,
    cover: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=400&fit=crop',
  },
  {
    id: 'c2',
    name: 'Ciclismo de Ruta Latam',
    sport: 'cycling',
    description: 'Comunidad de ciclistas de ruta. Compartimos rutas, consejos y organizamos rodadas.',
    members: 892,
    isJoined: false,
    cover: 'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800&h=400&fit=crop',
  },
  {
    id: 'c3',
    name: 'Triatlón Argentina',
    sport: 'triathlon',
    description: 'Para triatletas de todos los niveles. Entrenamiento, nutrición y motivación.',
    members: 654,
    isJoined: true,
    cover: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800&h=400&fit=crop',
  },
]

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Bowl de Quinoa y Aguacate',
    category: 'lunch',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
    prepTime: 15,
    calories: 420,
    protein: 18,
    carbs: 45,
    fats: 22,
    ingredients: ['Quinoa', 'Aguacate', 'Tomate', 'Espinaca', 'Aceite de oliva'],
    steps: ['Cocinar quinoa', 'Cortar aguacate', 'Mezclar ingredientes'],
    author: 'Chef Nutrición',
  },
  {
    id: 'r2',
    title: 'Smoothie Proteico de Banana',
    category: 'snack',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600&h=400&fit=crop',
    prepTime: 5,
    calories: 280,
    protein: 25,
    carbs: 38,
    fats: 5,
    ingredients: ['Banana', 'Proteína whey', 'Leche de almendras', 'Avena'],
    steps: ['Mezclar todos los ingredientes', 'Licuar hasta obtener consistencia suave'],
    author: 'Nutrición Deportiva',
  },
  {
    id: 'r3',
    title: 'Pasta Integral con Pollo',
    category: 'dinner',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop',
    prepTime: 25,
    calories: 520,
    protein: 42,
    carbs: 58,
    fats: 12,
    ingredients: ['Pasta integral', 'Pechuga de pollo', 'Tomate', 'Albahaca', 'Ajo'],
    steps: ['Cocinar pasta', 'Saltear pollo', 'Mezclar con salsa'],
    author: 'Cocina Fit',
  },
  {
    id: 'r4',
    title: 'Ensalada de Atún y Garbanzos',
    category: 'lunch',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
    prepTime: 10,
    calories: 350,
    protein: 28,
    carbs: 32,
    fats: 14,
    ingredients: ['Atún', 'Garbanzos', 'Lechuga', 'Tomate', 'Limón'],
    steps: ['Mezclar garbanzos y atún', 'Agregar vegetales', 'Aliñar con limón'],
    author: 'Recetas Saludables',
  },
]

export const MOCK_GOALS: Goal[] = [
  {
    id: 'g1',
    type: 'distance',
    target: 60,
    current: 42,
    unit: 'km',
  },
  {
    id: 'g2',
    type: 'time',
    target: 6,
    current: 4,
    unit: 'sesiones',
  },
  {
    id: 'g3',
    type: 'distance',
    target: 5000,
    current: 3200,
    unit: 'kcal',
  },
]

export const MOCK_TRAINING_PLANS: TrainingPlan[] = [
  {
    id: 'tp1',
    date: new Date().toISOString().split('T')[0],
    workouts: [
      {
        id: 'w1',
        time: '07:00',
        sport: 'running',
        title: 'Rodaje suave',
        description: 'Rodaje a ritmo cómodo',
        durationMin: 45,
        intensity: 'easy',
        completed: false,
      },
    ],
  },
]
